### ISSUE TITLE
"Renaming routes in your project" - not necessary for relative routes

### ISSUE THREAD

**Issue by fnimick** [vloddot/sveltekit-gh-pages-spa-template#1]
The `{base}/path/here` is only necessary when linking to paths such as `/path/here` - i.e. any link or navigation target that starts with a forward slash. Relative paths still work fine without any base path manipulation. It may be worth pointing this out.

**Comment by vloddot** [comment]
Are there relative paths in SvelteKit? I did not know of this, would be great if you can find me the documentation for this.

**Comment by fnimick** [comment]
This isn't a sveltekit feature but a standard HTML feature. i.e. a route to `/blog/[slug]` needs to have the base path prepended, but a link from `/blog/[slug]` to a different slug does not.

For example, on page `/blog/foo`, `<a href="bar" ....` will link to `/blog/bar` via the link relative to the current URL.

**Comment by vloddot** [comment]
Oh, hmm... will mention that, thanks for your issue!
